---
- name: Add BIG-IPs to BIG-IQ
  hosts: all
  connection: local
  vars_files:
    - inventory/group_vars/sjc2-bigiq-cm-01.yml
  roles:
    - { role: f5devcentral.f5ansible }
  
  tasks:
    - name: Discover BIG-IP 1 device and import config, use default conflict policy
      bigiq_device_discovery:
        provider:
          server: "{{ bigiq_onboard_server }}"
          user: admin
          password: "{{ bigiq_onboard_new_admin_password }}"
          validate_certs: no
        device_address: "{{ bigip1 }}"
        device_username: "{{ bigip1user }}"
        device_password: "{{ bigip1pass }}"
        conflict_policy: "{{ bigip1conflict }}"
        device_conflict_policy: "{{ bigip1device_conflict }}"
        versioned_conflict_policy: "{{ bigip1versioned_conflict }}"
        statistics:
          enable: "{{ bigip1device_statistics_enable }}"
          interval: "{{ bigip1device_statistics_interval }}"
          zone: "{{ bigip1device_statistics_zone }}"
          stat_modules:
            - "{{ bigip1device_statistics_module1 }}"
            - "{{ bigip1device_statistics_module2 }}"
            - "{{ bigip1device_statistics_module3 }}"
        modules: "{{ bigip1modules }}"
      register: result
      delegate_to: localhost

    - name: Assert Discover BIG-IP 1 device and import config, use default conflict policy
      assert:
        that:
          - result is changed
          - result is success

    - name: Discover BIG-IP 2 device and import config, use default conflict policy
      bigiq_device_discovery:
        provider:
          server: "{{ bigiq_onboard_server }}"
          user: admin
          password: "{{ bigiq_onboard_new_admin_password }}"
          validate_certs: no
        device_address: "{{ bigip2 }}"
        device_username: "{{ bigip2user }}"
        device_password: "{{ bigip2pass }}"
        conflict_policy: "{{ bigip2conflict }}"
        device_conflict_policy: "{{ bigip2device_conflict }}"
        versioned_conflict_policy: "{{ bigip2versioned_conflict }}"
        statistics:
          enable: "{{ bigip2device_statistics_enable }}"
          interval: "{{ big2p1device_statistics_interval }}"
          zone: "{{ bigip2device_statistics_zone }}"
          stat_modules:
            - "{{ bigip2device_statistics_module1 }}"
            - "{{ bigip2device_statistics_module2 }}"
        modules: "{{ bigip2modules }}"
      register: result
      delegate_to: localhost

