---
- name: Create applications SJC PME Lab F5 Networks
  hosts: all
  connection: local

  tasks:
    - name: site20waf.example.f5.com
      bigiq_application_https_waf:
        provider:
          server: 10.192.75.185
          user: admin
          password: admin
          validate_certs: no
        name: "site20waf.example.f5.com"
        wait: yes
        description: Load balance WAF
        service_environment: "bigip2.lab.fp.f5net.com"
        domain_names: "site20.example.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.201
            port: 80
          - address: 10.1.20.202
            port: 80
        inbound_virtual:
          address: 10.1.10.207
          netmask: 255.255.255.255
          port: 443
        redirect_virtual:
          address: 10.1.10.207
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site22http.example.f5.com
      bigiq_application_http:
        provider:
          server: 10.192.75.185
          user: admin
          password: admin
          validate_certs: no
        name: "site22http.example.f5.com"
        wait: yes
        description: Load balance HTTP
        service_environment: "bigip2.lab.fp.f5net.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.202
            port: 80
        inbound_virtual:
          address: 10.1.10.208
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site26https.example.f5.com
      bigiq_application_https_offload:
        provider:
          server: 10.192.75.185
          user: admin
          password: admin
          validate_certs: no
        name: "site26https.example.f5.com"
        wait: yes
        description: Load balance HTTPS Offload
        service_environment: "bigip2.lab.fp.f5net.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.204
            port: 80
          - address: 10.1.20.205
            port: 80
        inbound_virtual:
          address: 10.1.10.209
          netmask: 255.255.255.255
          port: 443
        redirect_virtual:
          address: 10.1.10.209
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost