---
- name: Create applications SJC PME Lab F5 Networks
  hosts: all
  connection: local

  tasks:
    - name: site10waf.example.com
      bigiq_application_https_waf:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site10waf.example.com"
        wait: yes
        description: Load balance WAF
        service_environment: "bigip1.lab.fp.f5.com"
        domain_names: "site10.example.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.201
            port: 80
          - address: 10.1.20.202
            port: 80
        inbound_virtual:
          address: 10.1.10.201
          netmask: 255.255.255.255
          port: 443
        redirect_virtual:
          address: 10.1.10.201
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost

    - name: site12http.example.com
      bigiq_application_http:
        provider:
          server: 10.192.75.180
          user: admin
          password: admin
          validate_certs: no
        name: "site12http.example.com"
        wait: yes
        description: Load balance HTTP
        service_environment: "bigip1.lab.fp.f5.com"
        add_analytics: yes
        servers:
          - address: 10.1.20.201
            port: 80
        inbound_virtual:
          address: 10.1.10.202
          netmask: 255.255.255.255
          port: 80
      delegate_to: localhost