---
- name: Create applications Seattle PME Lab F5 Networks
  hosts: all
  connection: local

  tasks:
    - name: site10waf.example.com
      bigiq_application_https_waf:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site10waf.example.com"
        wait: yes
        state: absent
      delegate_to: localhost

    - name: site12http.example.com
      bigiq_application_http:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site12http.example.com"
        wait: yes
        state: absent
      delegate_to: localhost

    - name: site14https.example.com
      bigiq_application_https_offload:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site14https.example.com"
        wait: yes
        state: absent
      delegate_to: localhost

    - name: site15fasthttp.example.com
      bigiq_application_fasthttp:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site15fasthttp.example.com"
        wait: yes
        state: absent
      delegate_to: localhost

    - name: site16fastL4tcp.example.com
      bigiq_application_fastl4_tcp:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site16fasL4.example.com"
        wait: yes
        state: absent
      delegate_to: localhost

    - name: site18udp.example.com
      bigiq_application_fastl4_udp:
        provider:
          server: 10.11.150.14
          user: admin
          password: admin
          validate_certs: no
        name: "site18udp.example.com"
        wait: yes
        state: absent
      delegate_to: localhost