---
- name: Set up a secondary CM BIG-IQ
  hosts: udf-bigiq-dcd-02
  vars_files:
    - inventory/group_vars/udf-bigiq-dcd-02.yml
  roles:
    - { role: f5devcentral.bigiq_onboard }

- name: Add DCD devices to CM device concurrently
  hosts: udf-bigiq-dcd-02
  vars_files:
    - inventory/group_vars/udf-bigiq-dcd-02.yml
  tasks:
    - name: Add DCD to CM
      include_role:
        name: f5devcentral.register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
