---
- name: Delete applications UDF blueprint
  hosts: all
  connection: local

  tasks:
    - name: Remove application
      bigiq_application_http:
        provider:
          server: 10.1.1.4
          user: admin
          password: admin
          validate_certs: no
        name: "site40.example.com"
        wait: no
        state: absent
      delegate_to: localhost

    - name: Remove application
      bigiq_application_http:
        provider:
          server: 10.1.1.4
          user: admin
          password: admin
          validate_certs: no
        name: "site36.example.com"
        wait: no
        state: absent
      delegate_to: localhost

    - name: Remove application
      bigiq_application_http:
        provider:
          server: 10.1.1.4
          user: admin
          password: admin
          validate_certs: no
        name: "site42.example.com"
        wait: no
        state: absent
      delegate_to: localhost

    - name: site38.example.com
      bigiq_application_http:
        provider:
          server: 10.1.1.4
          user: olivia
          password: olivia
          validate_certs: no
        name: "site38.example.com"
        wait: no
        state: absent
      delegate_to: localhost