bigiq_onboard_server: 10.1.1.12
bigiq_onboard_hostname: big-iq-cm-02.example.com
bigiq_onboard_node_type: cm
#bigiq_onboard_discovery_address: 10.1.10.12/24
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: purple123
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: purple123
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4
bigiq_onboard_dns_search:
  - example.com
bigiq_onboard_ntp_servers:
  - time.nist.gov
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: B1970-582364-948-9857046-6393697