bigiq_onboard_server: 10.1.1.4
bigiq_onboard_hostname: big-iq-cm.example.com
bigiq_onboard_node_type: cm
#bigiq_onboard_discovery_address: 10.1.10.4/24
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: purple123
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: purple123
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4
bigiq_onboard_dns_search:
  - example.com
bigiq_onboard_ntp_servers:
  - time.nist.gov
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: Q0558-866155-422-7867054-4573666
bigip1: 10.1.1.8
bigip1user: admin
bigip1pass: purple123
bigip1conflict: keep_version
bigip1cluster: BostonCluster
bigip1modules:
  - ltm
  - asm
  - afm
  - apm
  - dns
  - security_shared
bigip2: 10.1.1.10
bigip2user: admin
bigip2pass: purple123
bigip2conflict: keep_version
bigip2cluster: BostonCluster
bigip2modules:
  - ltm
  - asm
  - afm
  - apm
  - dns
  - security_shared
bigip3: 10.1.1.7
bigip3user: admin
bigip3pass: purple123
bigip3conflict: keep_version
bigip3modules:
  - ltm
  - asm
  - fps
  - dns
  - afm
  - security_shared
bigip4: 10.1.1.11
bigip4user: admin
bigip4pass: purple123
bigip4conflict: keep_version
bigip4modules:
  - ltm
  - asm
  - security_shared