---
# This file establishes the necessary resources on AWS to create a Demo Webserver using Ubuntu
- name: Create Ubuntu resources
  hosts: localhost
  vars_files:
    - ./config.yml

  tasks:
    - name: Ensure the VM is deployed to Azure
      azure_rm_deployment:
        state: present
        resource_group_name: "{{ PREFIX }}"
        template: "{{ lookup('file', 'arm/docker-simple-on-ubuntu.json') }}"
        parameters:
          adminUsername:
            value: "{{NODE_USER}}"
          adminPassword:
            value: "{{NODE_PASSWORD}}"
          dnsNameForPublicIP:
            value: null
          vmSize:
            value: Standard_F1
          vmName:
            value: "{{PREFIX}}-server"
          location:
            value: "{{DEFAULT_REGION}}"
          privateIPAddress:
            value: "{{NODE_ADDRESS}}"
          virtualNetworkName: 
            value: "{{VNET1}}"
          subnetName:
            value: "{{VNET_SUBNET1}}"
          addressPrefix:
            value: "{{VNET_CIDR_BLOCK}}"
          subnetPrefix:
            value: "{{SUBNET1_CIDR_BLOCK}}"

...