##################################################################################################
###########################         UPDATE VARIABLE BELOW          ###############################
##################################################################################################

# Select Azure Cloud: AzureCloud, AzureChinaCloud, AzureUSGovernment, AzureGermanCloud
AZURE_CLOUD: AzureCloud

SUBSCRIPTION_ID: <Subscription Id>
TENANT_ID: <Tenant Id>
CLIENT_ID: <Client Id>
SERVICE_PRINCIPAL_SECRET: <Service Principal Secret>
# web browser and access token to sign in (if set to yes, delete USERNAME AND PASSWORD variables)
USE_TOKEN: yes

# A unique searchable prefix to all resources which are created
# Use a prefix w/o spaces or special characters (NO MORE THAN 10 CHARACTERS, no end with - or special characters)
PREFIX: udf-<name>

# Select on of  the region below (default East US)
DEFAULT_REGION: eastus

# Update your SSH azure KEY
AZURE_SSH_KEY: <name_of_the_azure_key>

# Get the public IP of SEA-vBIGIP01.termmarc.com, go to Access Methods, e.g. nslookup 49efa5b7-224c-4e7b-9f04-cf52591ec443.access.udf.f5.com)
# Fill the IP address returned by the nslookup here
# /!\ IF THE IP ADDRESS ENDS WITH A x.x.x.0 (e.g. 129.43.54.0), DELETE YOUR DEPLOYMENT AND RESTART A NEW ONE.
CUSTOMER_GATEWAY_IP: 0.0.0.0

# Adjust the BIG-IP Version based on your region 
BYOL_BIGIP_VERSION: "ami-04e893bab1e8b9b10" # 

##################################################################################################
###############  DO NOT EDIT AFTER THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING  #################
##################################################################################################

# VNET cidr block should encompass the subnets you specify
VNET_CIDR_BLOCK: 172.200.0.0/16
SUBNET1_CIDR_BLOCK: 172.200.1.0/24
SUBNET2_CIDR_BLOCK: 172.200.2.0/24
SUBNET3_CIDR_BLOCK: 172.200.255.0/27

EXT_NETWORK_UDF_VPN: 10.1.10.0/24
LOCAL_GATEWAY: UDF
SHARED_KEY: 4UbtTd2CXf7PJxkt6qgz

# Ubuntu Web Server IP Address (in Subnet 2):
NODE_ADDRESS: 172.200.2.50
NODE_PORT: 80
VIRTUAL_SERVER_PORT: 80
POOL_MEMBER_PORT: 80

APP_NAME: "{{PREFIX}}-app-azure"

# BIG-IP Customer Gateway Config
ansible_ssh_user: "admin"
ansible_ssh_pass: "purPl3f5@rk"

bigip_rest_user: "admin"
bigip_rest_password: "purPl3f5@rk"

# BIG-IQ SSG CONFIG
BIGIP_USER: admin
BIGIP_PWD: "74ZEws7axzWdKBap3DkQ"

BIGIQ_HOST: localhost:8100
BIGIQ_URI: http://{{BIGIQ_HOST}}
BIGIQ_USER: admin
BIGIQ_PWD: "purPl3f5@rk"

# IP Address of BIG IQ setup as license provider
# This BIQ must have netowrk access to the VPC in which the BIG-IP VE will be created
BYOL_BIGIQ_HOST: 10.1.10.4
BYOL_BIGIQ_USER: admin
BYOL_BIGIQ_PWD: "purPl3f5@rk"
#BYOL_POOL_NAME: byol-pool
BYOL_POOL_NAME: byol-pool-perAppVE

PROTOCOL_PROFILE_CLIENT: tcp-lan-optimized
PROTOCOL_PROFILE_SERVER: tcp-lan-optimized
HTTP_PROFILE: http
#Comma separated, string encapsulated list of DNS IP addresses. Leave the outer single quotes in place
NTP_SERVER: time.google.com

SSG_NAME:               "{{PREFIX}}-azure-ssg"
CLOUD_ENVIRONMENT_NAME: "{{PREFIX}}-azure-environment"
CLOUD_PROVIDER_NAME:    "{{PREFIX}}-azure-provider"
DEVICE_TEMPLATE_NAME:   "{{PREFIX}}-azure-device-template"
TEMPLATE_NODE_NAME:     "{{PREFIX}}-azure-service-node"
TEMPLATE_POOL_NAME:     "{{PREFIX}}-azure-pool"
SERVICE_CATALOG_NAME:   "{{PREFIX}}-azure-service-catalog"
LTM_RESOURCE_NAME:      "{{PREFIX}}-azure-resource-name"
