---
- name: BIG-IQ and AS3 Lab - Task 6 - Create custom HTTP AS3 Template on BIG-IQ
  hosts: sjc2-bigiq-cm-01
  vars_files:
    - inventory/group_vars/sjc2-bigiq-cm-01.yml

  tasks: 
    - name: Get BIG-IQ Token POST /mgmt/shared/authn/login (auth_bigiq.json or auth_bigiq_radius.json)
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/authn/login
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','.auth_bigiq.json') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    - name: Task 6 - Create custom HTTP AS3 Template on BIG-IQ - POST /mgmt/cm/global/appsvcs-templates
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/cm/global/appsvcs-templates
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body:
          # used https://www.json2yaml.com/ to convert JSON declaration to YAML
          description: 'Task 6 - Create custom HTTP AS3 Template on BIG-IQ'
          name: "{{ task6_bigiq_custom_template }}"
          schemaOverlay:
            type: object
            properties:
              class: {}
              updateMode: {}
              schemaVersion: {}
              id: {}
              label: {}
              remark: {}
              constants: {}
              Common: {}
              controls: {}
              scratch: {}
            required:
            - class
            definitions:
              Pool:
                loadBalancingMode:
                  type: string
                  default: round-robin
                monitors:
                  type: array
                members:
                  type: array
              Service_HTTP:
                virtualPort:
                  type: integer
                  default: 8080
                  const: 8080
                virtualAddresses:
                  type: array
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - debug:
        var: json_response.json

### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

    - name: Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response_task

    - debug:
        var: json_response_task.json

    - name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json[0].results != 'pending'"
      retries: 20
      delay: 30

    - debug:
        var: json_response_task.json