---
- name: BIG-IQ and AS3 Lab - Example Demo App - HTTP Application Service
  hosts: "{{ env }}"
  vars_files:
    - inventory/group_vars/{{ env }}.yml

  tasks: 
    - name: Get BIG-IQ Token POST /mgmt/shared/authn/login (auth_bigiq.json or auth_bigiq_radius.json)
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/authn/login
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','{{ user }}') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    - name: Task 1 - HTTP Application Service - POST /mgmt/shared/appsvcs/declare?async=true
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/declare?async=true
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body:
          # used https://www.json2yaml.com/ to convert JSON declaration to YAML
          class: AS3
          action: deploy
          persist: true
          declaration:
            class: ADC
            schemaVersion: "{{ as3_schemaVersion }}"
            id: example-declaration-01
            label: example
            remark: Example- HTTP Application Service
            target:
              hostname: "BOS-vBIGIP01.termmarc.com"
            Task1:
              class: Tenant
              MyWebApp1http:
                class: Application
                template: http
                statsProfile:
                  class: Analytics_Profile
                  collectedStatsInternalLogging: true
                  collectedStatsExternalLogging: false
                  capturedTrafficInternalLogging: false
                  capturedTrafficExternalLogging: true
                  collectPageLoadTime: true
                  collectClientSideStatistics: true
                  collectResponseCode: true
                  sessionCookieSecurity: ssl-only
                serviceMain:
                  class: Service_HTTP
                  virtualAddresses:
                  - "10.1.10.115"
                  pool: web_pool
                  profileAnalytics:
                    use: statsProfile
                web_pool:
                  class: Pool
                  monitors:
                  - http
                  members:
                  - servicePort: 80
                    serverAddresses:
                    - "10.1.20.115"
                    shareNodes: true
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - debug:
        var: json_response.json

### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

    - name: Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response_task

    - debug:
        var: json_response_task.json

    - name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json[0].results != 'pending'"
      retries: 20
      delay: 30

    - debug:
        var: json_response_task.json