---
- name: Get BIG-IQ Facts
  hosts: all
  connection: local

  tasks: 
    - name: Get BIG-IQ ALL facts (need to pull experimental Ansible branch)
      bigiq_device_facts:
        provider:
          server: 10.1.1.4
          user: marco
          password: marco
          auth_provider: radius
          validate_certs: no
        gather_subset: all
      delegate_to: localhost

