---
- name: Delete the application
  hosts: bigiq-01
  vars_files:
    - ./config.yml
  connection: local

  tasks:
    - name: Remove application
      bigiq_application_https_waf:
        name: "{{APP_NAME}}"
        wait: yes
        state: absent
      delegate_to: localhost
