---
- name: Delete the HTTP application
  hosts: all
  connection: local

  tasks: 
    - name: Remove HTTP application 
      bigiq_application_http:
        provider:
          server: 10.1.1.4
          user: olivia
          password: olivia
          validate_certs: no
        name: "site22.example.com"
        wait: no
        state: absent
      delegate_to: localhost
